ERROR_CODE = {
    'SerialPortIsAlreadyOpen': 0,
    'SerialPortIsNotOpen': 1,
    'SerialPortReadFailed': 2,
    'SerialPortWriteFailed': 3,
    'SerialPortAccessDenied': 4,
    'SerialPortNotFound': 5,
    'SerialPortError': 6,
    'SetCommunicationTimeoutsFailed': 7,
    'GetCommunicationStateFailed': 8,
    'SetCommunicationStateFailed': 9,
    'ClearCommunicationErrorFailed': 10,
    'IllegalMessageLength': 11,
    'UnknownCommand': 12,
    'CRCVerificationFailed': 13,
    'MessageTransferFailed': 14,
    'WrongCRC': 15,
    'WrongResponseID': 16,
    'WrongResponseToken': 17,
    'BadAckCode': 18,
    'IllegalEntriesNumber': 19,
    'IllegalDeviceVersion': 20,
    'IllegalDeviceType': 21,
    'IllegalDeviceLicense': 22,
    'WrongDeviceTag': 23
}
