name: Bug Report
description: File a bug report
title: "Bug: "
labels: ["bug"]
projects: ["omerday/Neuroscience-of-Anxiety-Lab"]
assignees:
  - omerday
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: Who are you?
      placeholder: ex. Rany Abend
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, when did it happen, and what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
    id: task
    attributes:
      label: task
      description: In Which Task did it happen?
      options:
        - Doors
        - NPU
        - TIM
      default: 0
    validations:
      required: true
  - type: checkboxes
    id: consistent
    attributes:
      label: Consistency
      description: Does the issue happen consistently? i.e, everytime you run the task?
      options:
        - label: Consistent
          required: false
        - label: Inconsistent
          required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant Info
      description: Please share the output files or log files, as well as screenshots if exist.
      render: shell